baseURL = "https://instantiator.dev"
languageCode = "en"
DefaultContentLanguage = "en"
title = "instantiator.dev"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
# googleAnalytics = "G-SHE42ZWKEN"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true