baseURL = "https://instantiator.github.io"
languageCode = "en-us"
title = "Lewis Westbury"
theme = "uBlogger"

[params]
  version = "1.2.X"

  [params.social]
    Twitter = "instantiator"
    Linkedin = "lewiswestbury"
    GitHub = "instantiator"
    Medium = "@instantiator"
    Devto = "instantiator"
    Email = "lewis@cantab.net"
    RSS = true

  [params.home.profile]
    social = true

  [params.page]
     [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = true
      Tumblr = false
      HackerNews = false
      Reddit = false
      Evernote = true

[menu]
  [[menu.main]]
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = "See all posts"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = "See all tags"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = "See all categories"
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration
    noClasses = false